spring.datasource.url=jdbc:mysql://localhost:3308/crm_backend?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
# CACHE REDIS (UPSTASH)
# spring.cache.type=redis
# spring.data.redis.host=famous-earwig-96254.upstash.io
# spring.data.redis.port=6379
# spring.data.redis.password=gQAAAAAAAXf-AAIgcDJiMzUyYzZjNDQ3ZDA0ZDgyODY1YzM0ZDIyNDhhNTliYQ
# spring.data.redis.ssl.enabled=true